name: Build lunasea docker

on:
    workflow_dispatch:

jobs:
  build:
    name: Build lunasea docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/lunasea

      -
        name: Prepare lunasea
        run: |
          docker run -v $PWD/lunasea:/lunasea ghcr.io/jagandeepbrar/lunasea:stable mv /usr/share/nginx/html /lunasea
          ls -al ./lunasea/html

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/lunasea:latest
          labels: ${{ steps.meta.outputs.labels }}