name: Build lunasea docker

on:
    workflow_dispatch:

jobs:
  build:
    name: Build lunasea docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Prepare environment
        run: |
          git clone https://github.com/flutter/flutter.git flutter
          export PATH="$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter channel stable
          flutter upgrade
          git clone https://github.com/JagandeepBrar/lunasea.git lunasea
          cd lunasea
          flutter build web

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - 
      #   name: Build
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: Dockerfile
      #     platforms: |
      #       linux/amd64
      #       linux/arm64/v8
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_USERNAME }}/lunasea:latest